name: C/C++ CI

on: push

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: install cmake
      run: sudo apt install -y cmake
    - name: pre-reqs
      run: sudo apt install -y libopenblas-dev liblapack-dev libarpack2-dev libsuperlu-dev
    - name: install arma
      run: sudo apt install -y libarmadillo-dev
    - name: configure
      run: mkdir ./build && cd ./build && cmake .. -DUSE_R_LIBS=OFF
    - name: build
      run: cmake --build .
    - name: test
      run: ./tests/relix_test
